"use client";
import { ArrowLeftIcon } from "@heroicons/react/24/outline";
import Head from "next/head";
import CommentModal from "../../../components/CommentModal";
import Sidebar from "../../../components/Sidebar";
import Widgets from "../../../components/Widgets";
import Post from "../../../components/Post";
import Comments from "../../../components/Comments";
import { useRouter } from "next/navigation";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { db } from "../../../firebase";

import { AnimatePresence, motion } from "framer-motion";

export default function PostPage() {
  const router = useRouter();
  const { id } = useSearchParams();
  const [post, setPost] = useState();
  const [comments, setComments] = useState([]);
  const [newsResults, setNewsResults] = useState([]);
  const [randomUsersResults, setRandomUsersResults] = useState([]);

  const fetchNews = async () => {
    try {
      const response = await fetch(
        "https://saurav.tech/NewsAPI/top-headlines/category/sports/in.json"
      );
      const data = await response.json();
      setNewsResults(data.articles);
    } catch (error) {
      console.log("Error fetching news data:", error);
    }
  };

  const fetchRandomUserData = async () => {
    try {
      const response = await fetch(
        "https://randomuser.me/api/?results=30&inc=name,login,picture"
      );
      const data = await response.json();
      setRandomUsersResults(data.results);
    } catch (error) {
      console.log("Error fetching random user data:", error);
    }
  };

  useEffect(() => {
    fetchNews();
    fetchRandomUserData();
  }, []);

  // get the post data

  useEffect(
    () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
    [db, id]
  );

  // get comments of the post

  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", id, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setComments(snapshot.docs)
    );
  }, [db, id]);

  return (
    <div>
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}

        <div className="xl:ml-[370px] border-l border-r border-gray-200  xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
          <div className="flex items-center space-x-2  py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div className="hoverEffect" onClick={() => router.push("/")}>
              <ArrowLeftIcon className="h-5 " />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Tweet
            </h2>
          </div>

          <Post id={id} post={post} />
          {comments.length > 0 && (
            <div className="">
              <AnimatePresence>
                {comments.map((comment) => (
                  <motion.div
                    key={comment.id}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 1 }}
                  >
                    <Comments
                      key={comment.id}
                      commentId={comment.id}
                      originalPostId={id}
                      comment={comment.data()}
                    />
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          )}
        </div>

        {/* Widgets */}

        <Widgets
          newsResults={newsResults.articles}
          randomUsersResults={randomUsersResults.results}
        />

        {/* Modal */}

        <CommentModal />
      </main>
    </div>
  );
}
